# Generated by Django 4.2.6 on 2024-02-23 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('terrain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('mass', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='planets.planet')),
            ],
        ),
    ]
