# Generated by Django 4.2.6 on 2024-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_remove_planet_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='planet_images/'),
        ),
    ]
