# Generated by Django 4.2.6 on 2024-02-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_planet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='planet_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
