# Generated by Django 4.2.6 on 2024-02-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0005_resident_planet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='planet_name',
        ),
    ]
